name: daytistics
version: 0.0.0+2
publish_to: none
environment:
  sdk: '^3.6.0'
  flutter: 3.29.0
description: Daytistics is a cross-platform mobile app that enhances well-being by analyzing daily activities with AI.
dependencies:
  connectivity_plus: ^6.1.3
  cryptography: ^2.7.0
  cupertino_icons: '^1.0.8'
  flutter:
    sdk: flutter
  flutter_dotenv: '^5.2.1'
  flutter_env_native: '^0.1.0'
  flutter_riverpod: '^2.6.1'
  flutter_svg: '^2.0.17'
  google_fonts: '^6.2.1'
  google_sign_in: '^6.2.2'
  mock_supabase_http_client: '^0.0.3+1'
  modal_bottom_sheet: '^3.0.0'
  package_info_plus: ^8.2.1
  posthog_flutter: ^4.10.2
  riverpod_annotation: '^2.6.1'
  sentry_flutter: ^8.13.2
  settings_ui: ^2.0.2
  sign_in_with_apple: ^6.1.4
  supabase_flutter: '^2.8.3'
  table_calendar: '^3.2.0'
  url_launcher: '^6.3.1'
  uuid: '^4.5.1'
dev_dependencies:
  build_runner: '^2.4.14'
  custom_lint: '^0.7.1'
  flutter_lints: '^5.0.0'
  flutter_test:
    sdk: flutter
  mockito: '^5.4.5'
  pubspec_dependency_sorter: '^1.0.5'
  riverpod_generator: '^2.6.4'
  riverpod_lint: '^2.6.4'
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/svg/
    - assets/jpeg/
