name: Build Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'daytistics/**'
      - '.github/workflows/build-tests.yml'

jobs:
  build-test-android:
    name: Test if Android Build is Successful
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version-file: 'daytistics/pubspec.yaml'
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Download dependencies
        working-directory: daytistics
        run: flutter pub get

      - name: Create .env file
        working-directory: daytistics
        run: touch .env

      - name: Build Android Executable
        working-directory: daytistics
        run: flutter build apk

  build-test-ios:
    name: Test if iOS Build is Successful
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version-file: 'daytistics/pubspec.yaml'
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Download dependencies
        working-directory: daytistics
        run: flutter pub get

      - name: Create .env file
        working-directory: daytistics
        run: touch .env

      - name: Build iOS Executable
        working-directory: daytistics
        run: flutter build ios --no-codesign
