name: iOS Build and Deploy to App Store with Custom Version

on:
  push:
    branches:
      - daily-reminder-notification

env:
  FLUTTER_CHANNEL: "stable"
  RUBY_VERSION: "3.2.2"

jobs:
   build_ios:
    name: Build iOS
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: 'daytistics/ios'

      - name: Clean up vendor
        working-directory: 'daytistics/ios'
        run: rm -rf vendor

      - name: Install Bundler Gems
        working-directory: 'daytistics/ios'
        run: bundle install

      - name: Run Flutter tasks and get pub packages
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version-file: 'daytistics/pubspec.yaml'
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Get Flutter Packages
        working-directory: ./daytistics
        run: flutter pub get

      - name: Install Bundler Gems
        working-directory: 'daytistics/ios'
        run: |
          bundle install
          bundle exec pod repo update  # Add this line

      - name: List available Xcode versions
        run: xcode-select --switch /Applications/16.2.0.app

      - name: Reinstall Pods
        working-directory: 'daytistics/ios'
        run: |
          rm -rf Pods Podfile.lock
          bundle install
          bundle exec pod repo update
          bundle exec pod install --clean-install

      - name: Clean Flutter build
        working-directory: ./daytistics
        run: flutter clean

      - name: Create .env file
        working-directory: ./daytistics
        run: touch .env

      - uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'release_app_store'
          subdirectory: daytistics/ios
          options: '{
            "version_number": "${{ github.event.inputs.version }}", 
            "env_vars": ["SUPABASE_URL", "SUPABASE_ANON_KEY", "POSTHOG_API_KEY", "SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID", "SENTRY_DSN"]
            }'
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8_BASE64: ${{ secrets.ASC_KEY_P8_BASE64 }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID: ${{ secrets.SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

   
