name: dev-checks
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Install dependencies
        working-directory: ./daytistics
        run: flutter pub get
      - name: Create .env file
        working-directory: ./daytistics
        run: touch .env
      - name: Analyze code
        working-directory: ./daytistics
        run: flutter analyze

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Install dependencies
        working-directory: ./daytistics
        run: flutter pub get
      - name: Create .env file
        working-directory: ./daytistics
        run: touch .env
      - name: Run tests
        working-directory: ./daytistics
        run: flutter test
