name: Linting
on:
  pull_request:
    branches:
      - main
    paths:
      - 'daytistics/**'
      - '.github/workflows/lints.yml'
  workflow_dispatch:

jobs:
  analyze_flutter:
    name: Analyzing Flutter Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2

      - name: Install dependencies
        working-directory: ./daytistics
        run: flutter pub get

      - name: Create .env file
        working-directory: ./daytistics
        run: touch .env

      - name: Run built-in linter (Flutter)
        working-directory: ./daytistics
        run: flutter analyze

      - name: Run custom linter (Flutter)
        working-directory: ./daytistics
        run: dart run custom_lint

  analyze_deno:
    name: Analyzing Deno Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run linter (Deno)
        working-directory: ./daytistics
        run: deno lint