name: Deploy new Supabase project
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
    create-project:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Create new Supabase project
              run: |
                curl -X POST 'https://api.supabase.com/v1/projects' \
                --header 'Authorization: Bearer ${{ secrets.SUPABASE_PERSONAL_ACCESS_TOKEN }}' \
                --header 'Content-Type: application/json' \
                --data-raw '{
                    "name": "$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")",
                    "organization_id": "${{ secrets.SUPABASE_ORGANIZATION_ID }}",
                    "db_pass": "${{ secrets.SUPABASE_DB_PASS }}",
                    "region": "eu-west-1"
                }'