name: Unit Tests
on:
  push:
    branches:
      - main
    paths:
      - 'daytistics/**'
      - '.github/workflows/unit-tests.yml'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  flutter-unit-tests:
    name: Flutter Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2

      - name: Install dependencies
        working-directory: ./daytistics
        run: flutter pub get
      - name: Create .env file
        working-directory: ./daytistics
        run: touch .env
      - name: Run tests (Flutter)
        working-directory: ./daytistics
        run: flutter test